### ISSUE TITLE
Method name analyzers should not run run for override/implementing methods

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/AsyncUsageAnalyzers#30]
Currently the **UseAsyncSuffix** diagnostic is reported for cases where a method overrides a method from a base class and/or implements an interface method. In these cases, the name is set by the base definition, so no naming warnings should be reported at the site of an overriding or implementing method.

**Comment by ChrSteinert** [comment]
Isn't this duplicated by #33 ?

**Comment by ChrSteinert** [comment]
On second thought - this is also for `AvoidAsyncSuffixAnalyzer` isn't it?
