### ISSUE TITLE
UseAsyncSuffix should not fire for overriding methods

### ISSUE THREAD

**Issue by paulomorgado** [DotNetAnalyzers/AsyncUsageAnalyzers#33]
If the class being derived from is ill designed and doesn't suffix asynchronous methods with Async, there's nothing the derived class can do about it, so this should not be a warning.

**Comment by sharwell** [comment]
Agreed, we use the same convention in StyleCopAnalyzers.

**Comment by sharwell** [comment]
Duplicate of #30
