### ISSUE TITLE
Analyzers require mscorlib 2.0.5.0 because of JSON.NET

### ISSUE THREAD

**Issue by paulomorgado** [DotNetAnalyzers/AsyncUsageAnalyzers#34]
I'm getting this warning:

> MissingAnalyzerReference	Analyzer assembly 'packages\StyleCop.Analyzers.1.0.0-beta009\analyzers\dotnet\cs\Newtonsoft.Json.dll' depends on 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' but it was not found. Analyzers may not run correctly

**Comment by sharwell** [comment]
Duplicate of DotNetAnalyzers/StyleCopAnalyzers#1345.
