### ISSUE TITLE
Support Supression attribute

### ISSUE THREAD

**Issue by dersteve** [DotNetAnalyzers/AsyncUsageAnalyzers#45]
At the moment there is only support for "pragma" for supression of a rule.

It would be good to be consistent and support **SupressionAttribute** as well.

**Comment by sharwell** [comment]
If `SuppressMessage` is not working, you should probably file a bug in the [dotnet/roslyn](https://github.com/dotnet/roslyn) repository, since suppressions are handled entirely by the compiler itself. Do you have a specific example where we can see this failing?

**Comment by dersteve** [comment]
I just assumed it would not be working, because here [1] it talks only about the 'pragma approach'

[1] https://github.com/DotNetAnalyzers/AsyncUsageAnalyzers/blob/master/documentation/UseAsyncSuffix.md

**Comment by sharwell** [comment]
I filed #46 to get this addressed. :smile:
