### ISSUE TITLE
Update documentation to include [SuppressMessage] examples

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/AsyncUsageAnalyzers#46]
As mentioned in #45, the documentation for rules currently only includes examples for using `#pragma warning disable` to suppress violations. While `[SuppressMessage]` works as well, examples need to be created so users are aware of the option.

**Comment by dersteve** [comment]
I added the documentation for the existing documentation and created a pull request #47

**Comment by sharwell** [comment]
Fixed in #47
