### ISSUE TITLE
New rule proposal: Methods returning a Task should end with Async

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/AsyncUsageAnalyzers#7]
**Category:** Naming
**Rule:** Methods returning a `Task` should end with `Async`
**Description:** The manner in which asynchronous methods are consumed in code differs substantially from non-asynchronous methods. The [Task-based Asynchronous Pattern (TAP)](https://msdn.microsoft.com/en-us/library/hh873175.aspx) documentation, along with the .NET Framework itself, uses a specific naming convention to identify methods following one particular pattern for asynchronous method calls. This rule ensures other methods following this pattern do the same.

I was originally planning to file this as a new rule proposal for StyleCopAnalyzers. However, I decided to post it here since it likely applies to a wider range of code than StyleCopAnalyzers supports (e.g. VB code).

**Comment by jaredpar** [comment]
Seems like this should be more of a recommendation than a mandate rule.  I agree there is a strong correlation here between methods that return `Task` and operate asynchronously.  But there are also methods which synchronously return a `Task` value.

**Comment by sharwell** [comment]
There are a few such methods, but they are quite rare (rarely defined, not rarely used). It seems like that would be an appropriate place to suppress the warning. Remember that the exceptions aren't all cases where a method synchronously return a `Task`; it's only the methods that *by definition* synchronously return a `Task`.
