### ISSUE TITLE
New rule proposal: Called methods that are not marked async but return a task should be awaited

### ISSUE THREAD

**Issue by christopher-carson** [DotNetAnalyzers/AsyncUsageAnalyzers#76]
Discussed in dotnet/roslyn#20782. CS4014 is only reported if the callee is marked with async, this leaves out a good portion of the problem cases. It would be be helpful if an analyzer expanded on this to report on the cases where the method is not marked with async.

**Comment by sharwell** [comment]
This is already implemented in vs-threading as [VSTHRD110](https://github.com/Microsoft/vs-threading/blob/master/doc/analyzers/VSTHRD110.md).
